# Generated by Django 2.2.16 on 2022-07-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_engine', '0003_userranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentobject',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
