"""
Django settings for chess_backend project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import yaml

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '30yz433%xyb7kit$-$n%@-wn4th0q^%e5(mnb%@etc-kc^5mt^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
settings_path = '%s/core/config/settings.yml' % BASE_DIR
settings = yaml.load(open(settings_path))
if 'allowed_hosts' in settings:
    ALLOWED_HOSTS = settings['allowed_hosts']
print('ALLOWED_HOSTS : %s' % ALLOWED_HOSTS)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third part apps
    # 'rest_framework',
    # 'rest_framework.authtoken',
    # 'rest_framework_swagger',
    # 'drf_yasg',
    'widget_tweaks',

    # Project apps
    'chess_engine.apps.ChessEngineConfig',
]

# AUTH_USER_MODEL = 'users.User'  # rewrite users model for phone column

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'chess_game.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chess_game.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'NAME': 'chess_backend',
        'USER': 'root',
        'PASSWORD': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 跨域名settings
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ORIGIN_WHITELIST = (
    'example.com',
    'hostname.example.com',
    'localhost:8000',
    'localhost:8888',
    'localhost:4300',
    'localhost:4200',
    '127.0.0.1:8000',
    '127.0.0.1:4200',
)
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
)

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

# Login Redirect
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'

FIXTURE_DIRS = (
    os.path.join(BASE_DIR, "fixtures/"),
)

# REST_FRAMEWORK SETTINGS
# https://www.django-rest-framework.org/api-guide/settings/
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'chess_game.authtokens.authentication.TimedTokenAuthentication',
        'chess_game.authtokens.authentication.TimedURLTokenAuthentication',
        # enables simple commands line authentication
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        # 'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'register': '10/day',  # by ip
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': ('django_filters.rest_framework.DjangoFilterBackend',)
}


SIMPLEUI_LOGO = '/static/logo.png'
# SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60
SIMPLEUI_ICON = {
    'Payments & Transfers': 'fas fa-wallet',
    'Notifications': 'far fa-bell',
    'Beneficiaries': 'fas fa-donate',
    'Configs': 'fas fa-sliders-h',
    'Transfers': 'fas fa-exchange-alt',
    'Transactions': 'fas fa-receipt',
    'Sanction Countries': 'fas fa-flag',
    'Sanction banks': 'fas fa-money-check',
    'Sanction Entities': 'fas fa-stamp',
    'Sanction individuals': 'far fa-address-book',

    'Shop': 'fas fa-store',
    'Shops': 'fas fa-store',
    'Messages': 'far fa-envelope',
    'Requests': 'fas fa-angle-double-down',
    'System messages': 'far fa-comments',
    'Users': 'fas fa-users',
    'Bank': 'fas fa-credit-card',
    'Banks': 'fas fa-credit-card'

}

DATA_UPLOAD_MAX_NUMBER_FIELDS = None


# log path
LOG_ROOT = "./"
_console_level = 'DEBUG'
_log_filename = 'chess-game.log'

# user token settings
USER_TOKEN_INDEX_DURATION = 60 * 60 * 24
AUTH_TOKEN_VALID_DURATION = 60 * 20  # in seconds

# Static Files
STATIC_ROOT = '/chess_game/static'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
